repos:
  - repo: local
    hooks:
      - id: mvn-build
        name: "Maven Build"
        entry: mvn clean
        language: system
        always_run: true
        pass_filenames: false

      - id: mvn-test
        name: "Maven Test"
        entry: mvn clean test
        language: system
        always_run: true
        pass_filenames: false

      - id: java-fmt
        name: "Java (style) Formatter"
        entry: astyle --suffix=none
        language: system
        types: [file]
        files: ^.*\.java$
